{{/* 
Database Secret Template - Supports both MSSQL and Oracle
This template creates secrets for database credentials
*/}}
{{- if .Values.database.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.external.existingSecret }}
  labels:
    {{- include "user-onboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  # TODO: Replace with actual base64 encoded credentials
  # For MSSQL: username should be your SQL Server username
  # For Oracle: username should be your Oracle database username
  {{ .Values.database.external.secretKeys.username }}: {{ .Values.database.external.username | b64enc | quote }}
  # TODO: Replace with actual base64 encoded password
  # Use: echo -n 'your-password' | base64
  {{ .Values.database.external.secretKeys.password }}: "" # TODO: Add base64 encoded password
---
{{- end }}

{{/* JWT Keys Secret */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.security.jwtSecret }}
  labels:
    {{- include "user-onboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  # TODO: Replace with actual JWT RSA keys (base64 encoded)
  # Generate keys with: 
  # openssl genrsa -out private_key.pem 2048
  # openssl rsa -in private_key.pem -pubout -out public_key.pem
  # cat private_key.pem | base64 -w 0
  # cat public_key.pem | base64 -w 0
  private_key.pem: "" # TODO: Add base64 encoded private key
  public_key.pem: "" # TODO: Add base64 encoded public key

---
{{/* RabbitMQ Secret - Only if using external RabbitMQ */}}
{{- if and .Values.rabbitmq.enabled .Values.rabbitmq.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.external.existingSecret }}
  labels:
    {{- include "user-onboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
type: Opaque
data:
  # TODO: Replace with actual RabbitMQ credentials (base64 encoded)
  username: {{ .Values.rabbitmq.external.username | b64enc | quote }}
  password: "" # TODO: Add base64 encoded RabbitMQ password
{{- end }}
