apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-onboard.fullname" . }}-backend
  labels:
    {{- include "user-onboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "user-onboard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-onboard.fullname" . }}-frontend
  labels:
    {{- include "user-onboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "user-onboard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
{{- if and .Values.rabbitmq.enabled (not .Values.rabbitmq.external.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-onboard.fullname" . }}-rabbitmq
  labels:
    {{- include "user-onboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: management
  selector:
    {{- include "user-onboard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
{{- end }}

